# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(verbose_name='Document Link')),
                ('author_name', models.CharField(db_index=True, max_length=100, verbose_name='Author Name')),
                ('author_email', models.EmailField(db_index=True, max_length=254, verbose_name='Author Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type_short', models.CharField(db_index=True, max_length=5, unique=True, verbose_name='Document Type Short')),
                ('document_type_long', models.CharField(max_length=50, verbose_name='Document Type Long')),
                ('description', models.TextField(verbose_name='Document Type Description')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentType'),
        ),
    ]
